### ISSUE TITLE
newlines in google sheet cause tsv lines to be truncated

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/bat-co-roosting-database#1]
Some cells contains newlines. 

These newlines are included when exported to tsv. This causes GloBI to be confused in interpreting the provided indexing schema.

Suggest to remove all newlines that occur within cells.

**Comment by jhpoelen** [comment]
In LibreOffice Calc, you can find-replace newlines by using regular expressions. 

more specifically,

1. edit > `find and replace`
2. select "other options" 
3. enable "regular expressions"
4. enter ```\n``` in find field
5. keep replace field empty

See attached screenshot. 

![Screenshot from 2021-11-03 09-58-43](https://user-images.githubusercontent.com/1084872/140120677-04b54f19-40cf-4a1e-bdd2-7c59cd21d601.png)

**Comment by jhpoelen** [comment]
@ajacsherman I am having troubles incorporating your more recent bat-co-roosting data.

The main hurdle to automatically indexing your data appears to be newlines in the data cells. These newlines cause premature line breaks of individual data rows when exported in csv/tsv . 

I've outlined a recipe to remove the line breaks in https://github.com/globalbioticinteractions/bat-co-roosting-database/issues/1#issuecomment-959733825 and https://github.com/globalbioticinteractions/bat-co-roosting-database#updating . 

Also, I imagine that the a published version of the bat co-roosting dataset will live outside of Google Sheets in some data publication platform. 

Perhaps easiest is to release a copy of the bat-co-roosting database in csv/tsv/excel formats (all three) in Zenodo. Then, GloBI can use that to index the data.

Please advise.

**Comment by jhpoelen** [comment]
An example from attached copies extracted from https://docs.google.com/spreadsheets/d/1y5uBKvyzDQgQUtyRHvn5f20IOA7LoMho/edit#gid=691336520 -

 sheet | row number | format | column | value 
 --- | --- | --- | --- | ---
 interaction extract | 39 | tsv/csv | occurrenceId | `LunneyEtal1988-a16`
 interaction extract | 39 | xlsx | occurrenceId | `LunneyEtal1988-a16`
 interaction extract | 39 | google sheet | occurrenceId | `LunneyEtal1988-a16`
 interaction extract | 40 | tsv/csv | occurrenceId | ` Thirty roosts in 26 different trees were [...] diameter breast height over bark` 
 interaction extract | 40 | xlsx | occurrenceId | `DanielWilliams1983-a24`
 interaction extract | 40 | google sheet | occurrenceId | `DanielWilliams1983-a24`


Note that the csv/tsv exports provided by google sheets are malformed - line 40 in the csv/tsv versions contains a text fragment rather than the expected reference `DanielWilliams 1983-a24` .  

Suggest to remove newlines in the text fragments to make it easier to reuse the dataset.

screenshot of xlsx export: 

![image](https://github.com/globalbioticinteractions/bat-co-roosting-database/assets/1084872/9386bb08-f809-446b-956a-dcf9b0e1e8a8)

screenshot of csv/tsv export: 

![image](https://github.com/globalbioticinteractions/bat-co-roosting-database/assets/1084872/7e0bab10-75e5-47ec-8e68-b13d2856c0d0)

screenshot of google sheets user interface: 

![image](https://github.com/globalbioticinteractions/bat-co-roosting-database/assets/1084872/69e92358-0f8a-487a-b57a-6297dc4d06c1)

[WorkingDoc_Raw-Data-Extraction_ExpertLiterature_8_8.xlsx - interaction_extract.csv](https://github.com/globalbioticinteractions/bat-co-roosting-database/files/12525623/WorkingDoc_Raw-Data-Extraction_ExpertLiterature_8_8.xlsx.-.interaction_extract.csv)
[WorkingDoc_Raw-Data-Extraction_ExpertLiterature_8_8.xlsx](https://github.com/globalbioticinteractions/bat-co-roosting-database/files/12525624/WorkingDoc_Raw-Data-Extraction_ExpertLiterature_8_8.xlsx)

**Comment by n8upham** [comment]
Possible to do a find and replace for “\n” in the Google Sheet?  Looks like you can search using regular expressions, but if not this older solution could work: https://stackoverflow.com/questions/7528169/find-replace-commas-with-newline-on-google-spreadsheet

**Comment by jhpoelen** [comment]
@n8upham that'd be great if Google Sheet would be able to make this work! Curious what @ajacsherman has to say about your suggestion.

**Comment by jhpoelen** [comment]
Note that it appears that most newlines are embedded in text fragments of "interactionText" column (aka column AA)

**Comment by jhpoelen** [comment]
@ajacsherman used Google Sheet find-replace to:

1. replaced "\r\n" with " NEW_LINE " with "use regular expression" checked
2. replace all "\n" with " NEW_LINE " with "use regular expression" checked

Also, see attached screenshot of Google Sheet find-replace tool - 

![image](https://github.com/globalbioticinteractions/bat-co-roosting-database/assets/1084872/c0ca120c-e1f2-4778-a1ce-ba41750f1d8a)

**Comment by arw36** [comment]
Linking the protocol that was initially applied in Feb 2022 to avoid this issue: 

Google Sheet cleaning for integration with data analysis pipelines: 
To complete at the end of an extraction work session.
Text formatting 
- Remove leading and trailing white space 
- Remove line breaks in the "InteractionText" column 
- Find "\n" and replace with "" . Make sure "Match case" and "search using regular expressions" are checked. 
See tutorial: https://stackoverflow.com/questions/45850546/remove-line-break-within-cell-google-spreadsheet  


Was documented here: https://docs.google.com/document/d/1NRlq6P5LZmBG87phm_9uetf-miVev9vLQ0P4M9yfwK8/edit?usp=sharing

**Comment by jhpoelen** [comment]
@arw36 thanks Anna for pointing this out!

**Comment by jhpoelen** [comment]
Note that after "\r\n" and "\n" replaced by " NEW_LINE ", the data was able to be indexed without any manual steps.
