### ISSUE TITLE
suggest to update citation for full cetaf working group 

### ISSUE THREAD

**Issue by arw36** [globalbioticinteractions/bat-co-roosting-database#4]
as well as providing link to https://zenodo.org/record/6959687

**Comment by jhpoelen** [comment]
@arw36 just checked your access to this repository and as a maintainer, you should have access to make changes directly. Please let me know if you'd like me to do it for you.

**Comment by arw36** [comment]
Ok - I modified in the ReadMe. I couldn't see in the json since it looks more complicated than baseline template?

**Comment by jhpoelen** [comment]
@arw36 thanks for updating the citation in the README.md of the co-roosting dataset. I've also applied the citation to the `globi.json`. There must surely be a better way to capture the citation in a more structured way. Food for thought!
